### ISSUE TITLE
Only one live error message shows at a time, for validation on sign-up page

### ISSUE THREAD

**Issue by t1-tracey** [ncss/projects-2017-3#12]
Example: If you type a username that's too short, you get an error message as soon as you leave the field. Then if you move onto the nickname field and type a nickname that's too short and lose focus on the field, you get an error message for the nickname too.

Expected behaviour: both error messages should stay since they're relevant still.
What happens: the error message for the username disappears while the error message for nickname is still there.

I think it has something to do with when we make .text('error message etc ') appear in the `<p>`'s with `class="error"` — I don't know if it affects `<p>`'s that have already had their text changed or if it makes them blank. 

Here is part of the code for the username field:

<img width="476" alt="screen shot 2017-01-21 at 10 16 57 pm" src="https://cloud.githubusercontent.com/assets/22441348/22174014/6842eb1a-e027-11e6-8569-bc7785fa2178.png">

<img width="622" alt="screen shot 2017-01-21 at 10 21 48 pm" src="https://cloud.githubusercontent.com/assets/22441348/22174033/12c5e89e-e028-11e6-9c89-7ea9392ec07e.png">

Also I don't think having this repeated at the start of every blur event is a good idea hehe, it also might be affecting things:

```
var $form = $('form.sign-in');
    $('.error').html("");
```

I'm not quite sure what the second line does 😊 does it find a new tag with `class="error"` each time? Anyway, just recording some ideas :)

**Comment by t1-tracey** [comment]
Oh, or does `$('.error').html("")` make all the tags with `class=error` have blank text? 😮 🤔 I'll look into it ☺️ 😄

**Comment by t1-tracey** [comment]
Okay, just tested replacing the empty string in `$('.error').html("")` with something random (like `$('.error').html("food")`) and it did change all the error texts to `food` :)

**Comment by t1-tracey** [comment]
(Going to leave this for now)

**Comment by t1-tracey** [comment]
Thanks @lyneca 👍

**Comment by lyneca** [comment]
Calls to `.find()` can return more than one object

**Comment by lyneca** [comment]
I don't know much about the code, but are does `$input.parent().find()` contain just the element you want to change, or both error fields?

**Comment by t1-tracey** [comment]
Ooh thank you about `.find()` 😄 

I think so far it's been only one error field at a time that changes so it looks like `$input.parent().find()` just contains one field from what I can see...? but I'm not too sure. I'll take a look tomorrow 👍

**Comment by t1-tracey** [comment]
I have an idea for this, working on it now 😃

**Comment by t1-tracey** [comment]
Okay, I think the fix seems to be working for now at least 😃

<img width="545" alt="screen shot 2017-01-22 at 9 18 40 am" src="https://cloud.githubusercontent.com/assets/22441348/22178265/e50af346-e085-11e6-96af-b88c7dc6bcba.png">

**Comment by t1-tracey** [comment]
> **lyneca:**
> I don't know much about the code, but does `$input.parent().find()` contain just the element you want to change, or both error fields?

> **t1-tracey:**
> I think so far it's been only one error field at a time that changes so it looks like `$input.parent().find()` just contains one field from what I can see...? but I'm not too sure. I'll take a look tomorrow 👍

I'm just gonna take a look at this that Luke said earlier 😃

**Comment by t1-tracey** [comment]
Hmm it seems just to get one parent element? :thinking: I just had a quick check here https://api.jquery.com/parent/

**Comment by t1-tracey** [comment]
Oh, okay I see that `.find()` looks for descendants 😮 https://api.jquery.com/find/

**Comment by t1-tracey** [comment]
The hierarchy for the signup page is like this:

<img width="887" alt="screen shot 2017-01-22 at 9 48 18 am" src="https://cloud.githubusercontent.com/assets/22441348/22178490/d1246276-e08b-11e6-87bf-2c0d3ff0e321.png">

So from the jQuery API, it looks like that this —

[Uploading Screen Shot 2017-01-22 at 9.49.36 am.png…] (gonna fix this later)

gets the parent of the input element that's stored in the `$input` var, which will be a `<div>`. Then it looks for descendants of the `<div>` that are of class `error`, which will be the `<p>`. And its text will be set to whatever.

I didn't know that before 😊
