### ISSUE TITLE
Plain error messages

### ISSUE THREAD

**Issue by t1-tracey** [ncss/projects-2017-3#18]
Awesome that we have descriptive error messages coming up to notify users 👍 

Some of them come out as plain on a separate HTML page. It's not a bug - it's done intentionally - but @liamcal suggested we could add to the UX for those 🙂 

Here is a pic:
<img width="632" alt="screen shot 2017-01-24 at 4 04 04 pm" src="https://cloud.githubusercontent.com/assets/22441348/22234798/038c921e-e24f-11e6-9001-0e126f0f28cc.png">

List of error messages that come out as plain on a separate HTML page:
- [x] `Username already exists` after you choose a username that is already taken/if you choose a username that is not unique, on sign up page (`user.py`). <br><br>Thanks to @Jackywathy on [set up ajax on serverside and just-in-time testing for unique usernames](https://github.com/ncss/projects-2017-3/commit/4831b088e17fb6f02d681295ac0e884ffec04e20)

- [x] `Email is already registered` if the email you use is already in the db
<br> Again thanks to Jack! here in this commit 1f59c7e

- [x] `Username and password do not match` from sign in (`user.py`)
- [x] `Username cannot be found` from sign in (`user.py`)
- [x] `Uploaded file type not supported` when image type for uploaded profile pic or post image is not valid (`user.py`, `ask.py`)
<br> a basic version is done for sign up, but could be improved by retaining the value of the input posts. (For example, if you started filling in the username, nickname or email fields on signup, it should get that information and set the value of the input fields to it. Same with asking question. but maybe will leave for another time). signup page fix e09d7d9 & ask page fix 7f73aeb
- [x] `We couldn't find an uploaded file` if no image is uploaded to post (~`user.py`~, `ask.py`)
<br> edit: profile pic isn't necessary on sign up. fixed for ask page 7f73aeb (but again an enhancement, could retain values of other input fields if anything has been entered)

- [x] `You are not logged in` if you try to post a comment without being logged in (`view.py`)
<br> Yay d19d596 It prevents you from posting a comment in the first place if you're not logged in. Would be great to change the flow so that you can start a comment without being logged in, and then post it once you do log in. But this stops the error message from showing for now.
<br>
Actually something we could do here is not allow the user to post a comment front end (disable input field or anything) if there is no user_cookie, I'll look into that.

- [x] `Username is not in db` if you try to go to a URL of a profile that doesn't exist (`profile.py`)

The file name in brackets for items in the list indicates in which file(s) the message is being written. (I haven't actually gotten to verify these yet, I've only gone and looked in the files under `/back-end`)

These come from the lines `request.write()`. For example, in `back_end/user.py`:
<img width="557" alt="screen shot 2017-01-22 at 4 01 47 pm" src="https://cloud.githubusercontent.com/assets/22441348/22180165/b13a7172-e0bc-11e6-9a6e-883eae363d8e.png">

I quite like the idea of [live error messages that display right when you make the mistake](https://blog.codinghorror.com/the-just-in-time-theory/), hehe.

For example, I had changed it so that error messages appear live for the signup page, but that was adding onto @JackFrench's code using jQuery for validation of signup details 😃 I just found out that using JavaScript it's possible to change the text in the elements with `class=error`

I'm not sure how to take into consideration things from the database though — for example, to display an error message saying that a username is already taken on the sign up page, we need to check in the database.

And then if we wanted to make it a live error message (personal taste hehe), we'd need to be able to change the content on the HTML page, and I think there would be a way to do that...? but I am not sure hmm. Maybe sounds like using template language can do that? I'll have to look around for using the template language 🙂 (haven't gotten to see it in action much actually 😛)

EDIT:

Places where we could add an error message:
 - [x] When you go to the url of a post id that doesn't exist (for example `/view/10000` won't exist unless you create 10,000 posts), it should redirect to `/404`. That would require checking the largest post_id in the db though before redirecting 
<br/>
(e.g. if the largest post_id is only 10, there won't be more than 10 posts. So if someone tries to go to `/view/10000` it should take them to `/404` instead)

**Comment by t1-tracey** [comment]
I think it's awesome that we can put up these issues here, I might not have an idea for approaching a challenge but I'm able to document some thoughts and start something to keep track of things. And others can see it, and they might have some of their own ideas 😃

**Comment by t1-tracey** [comment]
Wow ooh being able to reorder the items in the checklist, that's pretty nifty 😎

**Comment by t1-tracey** [comment]
I noticed that we can use `render(context)` using the template engine render func before passing it into `request.write()` 🤔

**Comment by liamcal** [comment]
There's certainly a few different ways of doing most of them. Some might be able to be done entirely in the backend (eg, if the user isn't logged in, just don't show them the comment box. Otherwise, using some AJAX techniques might be the way to go for a few of them (create a python script to fulfil a specific purpose such as checking if a username already exists, then when the form is submitted, use jquery to send a POST request to that python script, retrieve the result and then continue validating using js). It might be a little complicated at first, but it's a cool thing to try and figure out.

**Comment by t1-tracey** [comment]
that does sound really cool 😄 ooh I hadn't thought about that — not showing the comment box on posts if you're not logged in, or maybe we could also have a message saying "You need to be logged in to add a comment" too. 

With the AJAX techniques, is it possible to check the username as soon as it's typed (e.g. in jQuery we can use the `blur()` event to check if something has lost focus) rather than wait until Submit is clicked? It sounds like it would be possible, since we've used an event for checking if Submit has been clicked too.

Oh wait, I think that was just for length validation and character validation, hmm. I think what I'm looking for there is at the bottom of `server.py`. 

I'll have to keep looking around :)

**Comment by Jackywathy** [comment]
Maybe putting a handler on "keyup" which waits a few seconds before sending an Ajax request (http://stackoverflow.com/questions/4220126/run-javascript)

**Comment by tracey-le** [comment]
hmm how do I reference a commit like 4831b08
oh okay, it does it automatically ^_^

**Comment by tracey-le** [comment]
I'm gonna try applying @Jackywathy's ajax techniques for some other error messages :D

**Comment by tracey-le** [comment]
@Jackywathy hey Jack :D I was just wondering for the keys in this dictionary:

<img width="990" alt="screen shot 2017-01-24 at 3 37 18 pm" src="https://cloud.githubusercontent.com/assets/22441348/22234331/797ed4e0-e24b-11e6-853b-21c3208351c3.png">

are the same ones as here on this reference site? http://api.jquery.com/jquery.ajax/

**Comment by Jackywathy** [comment]
yep should be, i just copied it off the book

**Comment by Jackywathy** [comment]
but make sure your passing $input.val(), not $input, cuz it gives you max recursion error if you dont
 :boom:
Took me ages to find out why it wasn't working before.

**Comment by tracey-le** [comment]
cool thank you! oh do you mean the rapid web dev book? I should check that!

oohh, oh noes thanks for the heads up! 👍

**Comment by tracey-le** [comment]
for the method we put in `post=` argument in `server.register()`, is that method called automatically whenever we do something like click a Submit button? (that sounds like magic 😯) I couldn't find on Tornado cheatsheet but maybe it'll be in web dev workbook.

**Comment by Jackywathy** [comment]
yep!
it sends it to post if you tell it to
```html
<form class="sign-in" action="/signup" method="post" enctype = "multipart/form-data">
```
&&
```js
$.ajax("/ajax/user_validate", {datatype: "json", type: "post", data: {username: $username.val()}
```
I think its get by default though

**Comment by tracey-le** [comment]
oooh okay thank you so much!! :DD

**Comment by tracey-le** [comment]
@Jackywathy oh noes I think I'm getting plain error message for `username already exists!` again on latest `dev` branch version... 🤔 ❔  your things seem to be there still, hmm

**Comment by tracey-le** [comment]
I remembered to check console

<img width="1197" alt="screen shot 2017-01-24 at 9 40 35 pm" src="https://cloud.githubusercontent.com/assets/22441348/22243985/d73e962e-e27d-11e6-8c6d-4a6f86d01fcd.png">

(not sure what it means but looks interesting, and strange ^_^)

I tried commenting out what I did in latest commit 90dabcb for #34 but it didn't affect anything (it was just using a var in template language)

**Comment by Jackywathy** [comment]
ooo thats not good :( it means that the handler is not returning anything. Ill have a look at it in a sec

**Comment by tracey-le** [comment]
oh @Jackywathy I just saw this 🤔 

<img width="563" alt="screen shot 2017-01-24 at 10 26 55 pm" src="https://cloud.githubusercontent.com/assets/22441348/22245519/5ff7f2c0-e284-11e6-9167-21f5fb92dcee.png">

check the changes in @ninjaprawn's latest commit to `db` maybe looks like merging problem ahaha (oh dear)

(I would link and take a closer look but I'm off for now 😴 night!)

**Comment by tracey-le** [comment]
got the link! see here 153542b

hehe sorry if this is appearing in everyone's mail, whoops... 😅

**Comment by tracey-le** [comment]
I have another idea

~- [ ] showing positive feedback when you have a valid username/nickname/email/password on the signup page~ (moved to bottom of page)

(see sign up page here for idea https://try.discourse.org :P)

e.g. 'Username is available' 'Valid password' 'Valid nickname'

**Comment by tracey-le** [comment]
wew I was just about to redirect /view/12345 to the 404 page (did it in commit a4ccecb) but just saw your changes in be33400 @Jackywathy Great idea with the error page :DD 

oh I think the changes don't clash though yay :))

**Comment by tracey-le** [comment]
yay did the same for profile pages — redirects to 404 when you go to a profile that doesn't exist commit 01fbde5

@StiffKelly I love our 404 page by the way hehe 😛 👌

**Comment by tracey-le** [comment]
@Jackywathy thanks for all the ajax help :DD

**Comment by tracey-le** [comment]
@Jackywathy I love this error page :)

<img width="1077" alt="screen shot 2017-01-29 at 9 32 22 pm" src="https://cloud.githubusercontent.com/assets/22441348/22403417/88f98bae-e66a-11e6-83f7-59abe8c5ca93.png">

**Comment by tracey-le** [comment]
weew recent commits to dev have been addressing the stuff for the sign in page

**Comment by tracey-le** [comment]
okay I think the main things are done ☺️ 😊 so I will close for now. but I will collect ideas for enhancements here

- [ ] showing positive feedback when you have a valid username/nickname/email/password on the signup page
<br> (see sign up page here for idea https://try.discourse.org :P) e.g. 'Username is available' 'Valid password' 'Valid nickname'

- [ ] if reload page for an error message, retain values of any other input fields.
<br>(For example, if you started filling in the username, nickname or email fields on signup, it should get that information and set the value of the input fields to it. Same with for asking question: if the page reloads because file not uploaded or because file type not supported, if you started entering a post title and description, we could make re-set the value of the input fields to keep those.)

- [ ] Would be great to change the flow so that you can start a comment without being logged in, and then post it once you do log in. (again, retaining the value of the input fields)

should I store these in a new issue? maybe I will

also would like to add that @Jackywathy error pages are very cool :DD
