### ISSUE TITLE
Syntax Error on line 46, validate.js (signup-validation-test)

### ISSUE THREAD

**Issue by Jackywathy** [ncss/projects-2017-3#20]
Well if you fix the syntax error it turns the new syntax highlighting off for some reason?
![capture](https://cloud.githubusercontent.com/assets/17282376/22205092/6dc88204-e1c9-11e6-9b73-c0ca7997244b.PNG)

**Comment by Jackywathy** [comment]
It looks like the whole validate.js file is not loaded, and it is using the "required" attribute for forms to generate an error message if the field is empty.

**Comment by t1-tracey** [comment]
Hi Jack :D oh, where can I look at it? sorry I'm not very familiar with using browser console hehe

<img width="1194" alt="screen shot 2017-01-24 at 9 15 55 am" src="https://cloud.githubusercontent.com/assets/22441348/22225245/d7b51d48-e215-11e6-926d-aa3190778c6c.png">

but this is what it looks like to me from Safari at the moment I think? oh and I am looking from `master`. signup-validation-test is already merged and it can be deleted but I just kept it so i could look at it still ^_^ 😊

**Comment by Jackywathy** [comment]
which branch should i be using? I was using the signup-validation branch but i see its behind master a lot now

**Comment by tracey-le** [comment]
sorry about confusion, I deleted signup-validation after it was merged cos I was just using it then but finished the 'test' I was doing with the blur() jQuery event (which I ended up including in the project anyway). 

I think you can go in dev or make another branch if you want to :D

**Comment by tracey-le** [comment]
@Jackywathy is this okay now? 😃 (this issue)

**Comment by Jackywathy** [comment]
yep i was using an older commit :smile:

**Comment by tracey-le** [comment]
okay :D
