### ISSUE TITLE
tuple unpacking in template engine (for loops)

### ISSUE THREAD

**Issue by Jackywathy** [ncss/projects-2017-3#26]
its not really necessary but it would be cool!

**Comment by tracey-le** [comment]
ooh
<img width="771" alt="screen shot 2017-01-24 at 12 26 37 pm" src="https://cloud.githubusercontent.com/assets/22441348/22230235/85c571a2-e230-11e6-895a-c988f2cceac5.png">

hehe http://www.ncss.edu.au/ckeditor_assets/attachments/38/template-language.pdf
