### ISSUE TITLE
Cannot paste into any input forms on sign-up page

### ISSUE THREAD

**Issue by Jackywathy** [ncss/projects-2017-3#31]

**Comment by tracey-le** [comment]
hmm 🤔 I just know that there is the `.on("paste")` event for jQuery

let me get the link

**Comment by tracey-le** [comment]
http://stackoverflow.com/questions/8747439/detecting-value-change-of-inputtype-text-in-jquery

I haven't checked if it actually works, but I did implement it for the live error messages on the signup page, with `.on("keyup paste change")`

trying to find this on site took way too long, GitHub (is there a quicker way than ncss/projects-2017-3 > branches > dev > commits? I tried searching but nothing comes up, and all the commits don't seem to appear on GitHub Desktop)

**Comment by tracey-le** [comment]
hmm okay what it does do is trigger the validation check when I try to paste into a sign up input field. but the pasted text doesn't appear. indeed it is a bug 🤔

**Comment by tracey-le** [comment]
oh, the other input forms appear to work (such as on `sign-in`). maybe this is just on `signup`

**Comment by tracey-le** [comment]
okay, looks like the `.on("paste")` wasn't actually what I thought it did. I did a test remove and it worked — when you paste in something, the text appears and the site validates it as soon as you do so. will fix for all the fields on signup!

**Comment by tracey-le** [comment]
I think this seems fixed now

:D
