### ISSUE TITLE
Question: does User.update_some() update the values for all users in db?

### ISSUE THREAD

**Issue by tracey-le** [ncss/projects-2017-3#35]
(Not really an issue or idea, just to keep track of something)

I'll look around later, but I thought it would be like User.update() which does only for certain user

How do I update for a specific user? I thought we were using update_some but that does for all, so I'm just gonna use User.update() for time being

**Comment by ninjaprawn** [comment]
This has been replaced in #25. In that you will be able to directly set the properties of a User instance, and that will update the appropriate entry in the database.

**Comment by tracey-le** [comment]
I also have another question, 

- [ ] how to set default comments for posts to be an empty list when you create it

cos at the moment it isn't. but maybe I tampered with something. so this is more a todo for myself to look at/keep track of

edit: this is now new issue — somehow on my branch, when I make a new post, a Comment object is created for it, but you can't even access its properties anyway because its like a NoneType or something 😕 

I might make separate branch and commit so I can share and keep track of changes

what ill do next: try putting in `post.all_comments()` and see what comes out immediately after I create the post

(gonna leave for another time, right now —> 😴)

**Comment by tracey-le** [comment]
@ninjaprawn ohhh thank you so much, now I realise how helpful #25 is going to be 😂 awesome of you to want to make db easier to use!

**Comment by tracey-le** [comment]
I am editing the files quite a bit too...so probably will be merge conflicts :]

**Comment by tracey-le** [comment]
my question has been answered so I shall close this for now ☺️
