### ISSUE TITLE
Two password fields on signup page for verification

### ISSUE THREAD

**Issue by tracey-le** [ncss/projects-2017-3#37]
Have two password fields on signup page so user can check that they've entered password as they expected

**Comment by Jackywathy** [comment]
i think i just implemented this **lets hope nothing 💥 's**

**Comment by tracey-le** [comment]
@Jackywathy that is awesome 😱😄😄😄😄 hehe (🤞!)

**Comment by tracey-le** [comment]
ooh so awesome to see you try implement this!

I just tried this though, on sign up page: e.g. 

Username: `username`
Nickname: `nickname`
Password: `password`
Repeat Password: `passwordz`
Email: `email@email.com`

but there were no live error messages and the password saved as `passwordz` cos it wouldn't accept `password` when I tried to sign in again 🤔

**Comment by Jackywathy** [comment]
I get this
![capture](https://cloud.githubusercontent.com/assets/17282376/22394226/40891dd2-e56e-11e6-8b40-7ddfde0ab27e.PNG)

Maybe try clear cache and pull from dev

**Comment by tracey-le** [comment]
ooh okay, I will find out how to clear cache for my browser
yup I have pulled from dev :D thanks Jack!

**Comment by tracey-le** [comment]
ooh it worked 😮 the password validation is awesome!! thanks again 😄😄

**Comment by Jackywathy** [comment]
@t1-tracey np

**Comment by tracey-le** [comment]
I will close this for now, do you think that will be okay?

**Comment by Jackywathy** [comment]
yep
