### ISSUE TITLE
Bug in server.py

### ISSUE THREAD

**Issue by Jackywathy** [ncss/projects-2017-3#49]
```python
server.register(r'/ajax/signin_username' , _405_handler, post=ajax.username_exists_handler)
```

Traceback (most recent call last):
  File "server.py", line 109, in <module>
    server.register(r'/ajax/signin_username'    , _405_handler                     , post=ajax.username_exists_handler)
AttributeError: module 'back_end.ajax' has no attribute 'username_exists_handler

I have commented it out for now. I think it might be a merge error but 'username_exists_handler' is not in backend!

**Comment by tracey-le** [comment]
hmm I think I removed it, do you have the latest version of dev?

**Comment by tracey-le** [comment]
yeah I did remove it, let me fix that in latest version of dev

**Comment by tracey-le** [comment]
yay, great bug reporting @Jackywathy :D yep 'twas just a merge error
