### ISSUE TITLE
Example of an issue e.g. add monkey route

### ISSUE THREAD

**Issue by juliawong** [ncss/projects-2017-3#8]
Here is where you provide more details (if there are any). 

Please add this new route: `/monkey` for Easter egg purposes.

**Comment by tracey-le** [comment]
lol I want to do this now

**Comment by tracey-le** [comment]
any pics of our merge monkey lying around?

**Comment by tracey-le** [comment]
The route exists now hehe 2fc5a98

to edit what shows up when you go to `/monkey`, see `monkey.html`

🙊🐵

**Comment by ninjaprawn** [comment]
Nice meme
